apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
meta
  name: nproject-app-podmonitor
  namespace: default
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: nproject-app
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    interval: 30s
