apiVersion: v1
kind: Service
metadata:  # ← Исправлено с "meta" на "metadata"
  name: nproject-app-svc
spec:
  type: LoadBalancer
  selector:
    app: nproject-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000