apiVersion: v1
kind: Service
meta
  name: nproject-app-svc
spec:
  # УБРАЛИ type: LoadBalancer — теперь будет ClusterIP (по умолчанию)
  selector:
    app: nproject-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000